version: '3'
services:
  web:
    build: .\app
    ports:
      - "5000:5000"
    environment:
      - HUGGINGFACE_TOKEN=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
    depends_on:
      - chromadb
  chromadb:
    image: chromadb/chroma  
    ports:
      - "8000:8000"